Emit more events from Scene3D
ignitionrobotics/ign-gui pull request #213
Opened 2021-04-27 15:53 UTC by chapulina

# 🎉 New feature

Closes #209

## Summary

This PR makes the 3D scene emit more events, such as clicks and hover, that can be used by other plugins. Most of the code here has been ported from [ignition::gazebo::Scene3D](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/src/gui/plugins/scene3d/Scene3D.hh).

I got stuck writing tests for it though, for some reason the render engine plugin is not properly loaded. I spent some time digging deep into `ign-plugin` with no luck. I'll leave this as draft until I can address this.

## Test it

I'd like to add an example plugin that makes use of these events, so others can use it as a pattern to copy for their needs.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests - **that's the tough part**
- [ ] Added example and/or tutorial - **TODO**
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# ➡️ Forward port

Port <FROM_BRANCH> to <TO_BRANCH>

Branch comparison: https://github.com/ignitionrobotics/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# 🎈 Release

Preparation for <X.Y.Z> release.

Comparison to <x.y.z>: https://github.com/ignitionrobotics/<REPO>/compare/<LATEST_TAG_BRANCH>...<RELEASE_BRANCH>

Needed by <PR(s)>

## Checklist
- [ ] Asked team if this is a good time for a release
- [ ] There are no changes to be ported from the previous major version
- [ ] No PRs targeted at this major version are close to getting in
- [ ] Bumped minor for new features, patch for bug fixes
- [ ] Updated changelog
- [ ] Updated migration guide (as needed)
- [ ] Link to PR updating dependency versions in appropriate repository in [ignition-release](https://github.com/ignition-release) (as needed): <LINK>

**Note to maintainers**: Remember to use **Squash-Merge**

2021-04-29 18:30 UTC, chapulina commented
I removed the tests that weren't working and ticketed #216. Opening this for review.

It's worth reading the conversation on #209. The current approach to emitting events is necessary for some use cases, but adds unnecessary complexity for others. I think we could revisit the current architecture in a future release in favor of an `objectName`-based approach for specific use cases.

2021-05-08 00:08 UTC, scpeters commented
I've fixed the issue with loading the render engines documented in #216 and have merged those changes into this branch. I moved `Scene3D_TEST.cc` to `test/integration`, and it seems to be working now.

2021-05-14 23:45 UTC, chapulina commented
I added a test for the `render` event in 23c0578. I won't have time to add tests for the other events for a while. Options:

1. Get this in with the current tests and add more tests later (this is already more testing than most plugins)
2. Someone else picks up this PR and adds tests for the click and hover events
3. Wait until I come back

2021-05-15 02:05 UTC, scpeters commented
> I added a test for the `render` event in [23c0578](https://github.com/ignitionrobotics/ign-gui/commit/23c057865ed3f50268bd4a94f6ac57c03fb25973). I won't have time to add tests for the other events for a while. Options:
> 
> 1. Get this in with the current tests and add more tests later (this is already more testing than most plugins)
> 2. Someone else picks up this PR and adds tests for the click and hover events
> 3. Wait until I come back

I can try adding some more tests. Do you know how to create fake mouse clicks from a test?

2021-05-25 20:38 UTC, scpeters commented
I just noticed the windows build has been broken since 23c0578

~~~
error C2491: 'ignition::gui::TestHelper::staticMetaObject': definition of dllimport static data member not allowed
~~~

2021-05-27 06:57 UTC, scpeters commented
I've added some expectations about the value of the `Vector3d` passed with the click events in 48171dd, and if CI is reasonable, then I will be ready to approve

2021-05-27 07:01 UTC, ahcorde requested changes

2021-05-27 07:01 UTC, ahcorde commented on test/integration/scene3d.cc
> +                << hoverToScene->Point() << "]" << std::endl;
Remove this trace ?

2021-05-27 07:11 UTC, scpeters commented on test/integration/scene3d.cc
> +                << hoverToScene->Point() << "]" << std::endl;
039ef43

2021-05-27 07:37 UTC, scpeters approved these changes

2021-05-27 09:44 UTC, ahcorde approved these changes

2021-05-27 09:44 UTC, merged