Added key modifiers to the click events
ignitionrobotics/ign-gui pull request #228
Opened 2021-05-28 08:45 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🎉 New feature

Related with this issue https://github.com/ignitionrobotics/ign-gui/issues/209. I added key modifiers: Alt, control and shift to the left and right clicks

## Summary

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-06-11 16:25 UTC, mjcarroll approved these changes
LGTM, but the `INTEGRATION_Scene3d` test is segfaulting now.

2021-06-11 17:29 UTC, mjcarroll commented
@osrf-jenkins retest this please

2021-06-14 21:22 UTC, chapulina reviewed
Have you looked into the `INTEGRATION_Scene3d` test failure?

2021-06-14 21:22 UTC, chapulina commented on include/ignition/gui/GuiEvents.hh
> +        static const QEvent::Type kType = QEvent::Type(QEvent::MaxUser - 10);
Why skip `-8` and `-9`?

2021-06-14 21:27 UTC, chapulina commented on include/ignition/gui/GuiEvents.hh
> +        static const QEvent::Type kType = QEvent::Type(QEvent::MaxUser - 10);
Oh I see them in https://github.com/ignitionrobotics/ign-gui/pull/224

2021-06-17 21:35 UTC, chapulina requested changes
Do you have a PR that uses these events, @ahcorde ? It would be nice to make sure the events have everything we need before merging and releasing. These classes don't use the PIMPL pattern, so if we realize later that they need more fields, we can't break ABI. See https://github.com/ignitionrobotics/ign-gui/issues/209#issuecomment-849808255 for more context.

2021-06-18 17:25 UTC, ahcorde commented
@chapulina this PR make use of it https://github.com/ignitionrobotics/ign-gui/pull/231/

2021-06-22 21:31 UTC, ahcorde commented
friendly ping @chapulina

2021-06-23 00:05 UTC, chapulina commented
@ahcorde , how about we target this one at `main` so we can iterate on it a bit. Then if we see the need to backport we can. It doesn't look like we have a use case for this on Citadel yet, right?

2021-06-23 07:09 UTC, ahcorde commented
I will wait to this forward port https://github.com/ignitionrobotics/ign-gui/pull/238 because it includes the scene3d tests.

2021-06-25 10:22 UTC, ahcorde commented
@chapulina retargeted to `main` and add PIMPL pattern

2021-06-25 22:46 UTC, chapulina approved these changes
I pushed some documentation and tweaks in edcfb77be72a9f25b7edd4f5043c4e1d7d873fc4.

I'm on the fence about keeping both the `ClickOnScene` and `ClickToScene` events. I think they could be combined into a single event to avoid confusion. But I'll refrain from making more changes until @scpeters opens a PR adding the distance field as proposed in https://github.com/ignitionrobotics/ign-gui/issues/209#issuecomment-849808255.

Let's go with these for now!

2021-06-25 23:15 UTC, merged