3 ➡️ 4
ignitionrobotics/ign-gui pull request #234
Opened 2021-06-18 00:06 UTC by chapulina

# ➡️ Forward port

Port `ign-gui3` to `ign-gui4`

Branch comparison: https://github.com/ignitionrobotics/ign-gui/compare/ign-gui4...ign-gui3

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

2021-06-18 07:34 UTC, ahcorde requested changes
it requires a `ignition-rendering4` release

2021-06-21 07:02 UTC, ahcorde commented
@osrf-jenkins retest this please

2021-06-21 07:28 UTC, ahcorde commented
MacOS failure depends on this PR https://github.com/osrf/homebrew-simulation/pull/1517

2021-06-22 02:37 UTC, adlarkin approved these changes

2021-06-22 02:51 UTC, merged