Added Snackbar qtquick object
ignitionrobotics/ign-gui pull request #369
Opened 2022-03-07 14:14 UTC by ahcorde

# 🎉 New feature

## Summary

Create a IgnSnackBar QtQuick object to show message to the user in the same manner by plugins

It could be :
 - persistant and then you need to click inside the GUI
 - or with a timeout

![snackback](https://user-images.githubusercontent.com/1933907/157050308-49881fbe-78af-4e81-9b89-584983d4d708.gif)

Added snackbar dialog to:
 - Save configuration
 - Teleop topic
 - Snapshot
 - Image view update

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-03-07 18:00 UTC, chapulina requested changes
+1 to the centralized approach using a signal from the `MainWindow` :+1: This should make it easier to improve the snackbar in the future. For example, in the future, if we start getting too many notifications at once, we may want to implement some logic to display them consecutively.

2022-03-07 18:00 UTC, chapulina commented on include/ignition/gui/MainWindow.hh
> +      signals: void notifyWithDuration(const QString &_message, int _duration);
Missing `param` docs

2022-03-07 18:00 UTC, chapulina commented on include/ignition/gui/qml/IgnSnackBar.qml
> +    color: "#c9daf8"
We should avoid using custom colors as much as possible and instead use colors from the current palette (`Material.primary`, `Material.accent`, `Material.background`). 

The [official spec](https://material.io/components/snackbars#anatomy) recommends a grey color, but I think QtQuick doesn't make it straight-forward to have that follow a dark / light theme. So I think we could stick to `Material.background` here.

2022-03-07 18:00 UTC, chapulina commented on src/plugins/teleop/Teleop.cc
> +      QString::fromStdString("A new topic has been entered: '" +
How about:

```suggestion
      QString::fromStdString("Subscribing to topic: '" +
```

2022-03-07 18:00 UTC, chapulina commented on include/ignition/gui/qml/IgnSnackBar.qml
> +  property int duration: 1000
I'm finding 1 second too short to read some of the snackbars on this PR. The Material spec [recommends](https://material.io/components/snackbars#behavior) "_They automatically disappear from the screen after a minimum of four seconds, and a maximum of ten seconds._", so how about defaulting to `4000` and using that throughout this PR?

2022-03-09 19:31 UTC, chapulina approved these changes
LGTM! I just pushed a small change in eb58ef3aa3f05a6a379bfc2cb3052e709e658351 to change the border to a shadow.

Before:

![border](https://user-images.githubusercontent.com/5751272/157517406-093a1a19-b7e3-4f3c-9721-a64f26e8595c.png)

After:

![shadow](https://user-images.githubusercontent.com/5751272/157517444-2cfcae92-8b22-468c-b845-7601b745377b.png)

2022-03-09 20:01 UTC, merged

2022-04-13 21:31 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-04-13-fortress-edifice/1367/1